sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es5b
sonar.projectName=yovi_es5b

sonar.sources=webapp/src,users/service,users/models,users/validator,users/config,gamey/src
sonar.tests=webapp/src,users/__tests__,gamey/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.test.js
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info

sonar.cpd.exclusions=webapp/src/i18n/resources.ts
sonar.coverage.exclusions=webapp/src/i18n/resources.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.min.js,users/errors.js,users/openapi.yaml

sonar.exclusions=webapp/src/main.tsx, **/*.png, **/*.jpg, **/*.svg, **/*.css, **/node_modules/**, **/dist/**
