ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Estrategia de Solución

=== Tecnologías seleccionadas
Basándonos en los requisitos del proyecto, se han seleccionado las siguientes tecnologías para garantizar un sistema modular y eficiente:

* Frontend:

** *React con Vite*: Para construir una interfaz de usuario rápida y reactiva como Single Page Application (SPA).

** *TypeScript*: Añade tipado estático para reducir errores en el desarrollo del frontend.

* Backend de Usuarios:

** **Node.js & Express**: Entorno ligero y escalable para gestionar la lógica de usuarios y la API REST.

** **express-session**: módulo de Express para gestionar la autenticación mediante cookies de sesión

* Motor de Juego:

** **Rust**: alto rendimiento y seguridad de memoria para el motor de juego y la lógica de bots.


* Persistencia y Datos:

** **MySQL**: base de datos relacional para gestionar de forma eficiente el modelo de datos de la aplicación, el cual sigue una estructura relacional.

** **Sequelize**: ORM de MySQL para facilitar la interacción con el modelo relacional de la aplicación.

* Orquestación:

** **Docker**: se utiliza Docker para la orquestación y despliegue de los distintos contenedores que forman la aplicación.

* Pruebas:

** Pruebas unitarias: se utiliza la biblioteca **vitest** y las herramientas estandar de Rust de pruebas unitarias.

** Pruebas de aceptación: se utilizan las bibliotecas **vitest** y **playwright**.

=== Decisiones de organización del equipo

Se utilizan las siguientes herramientas de GitHub:

* Sistema de issues
* Sistema de pull requests para revisión de código
* Proyectos y vista de kanban para gestión de issues
* Wiki de GitHub para el registro de acta, decisiones y guías misceláneas.

Las comunicaciones en tiempo real se llevarán a cabo mediante Whatsapp o Discord.

Se asigna a cada miembro del equipo la responsabilidad de ser capaz de entender el comportamiento general del resto de miembros del equipo, independientemente de qué parte del código haya programado el mismo.
